version: 2.1

commands:
  install-dependencies:
    steps:
      - restore_cache:
          key: app-v1-cache-{{ checksum "package-lock.json" }}
      - run:
          name: "Install Client Dependencies"
          command: npm install
      - run:
          name: "Install Server Dependencies"
          working_directory:  ~/twilio-voice-notification-app/server
          command: npm install
      - save_cache:
          key: app-v1-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./server/node_modules

jobs:
  build-and-test:
    working_directory: ~/twilio-voice-notification-app
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - install-dependencies
      - run:
            name: "Setting environment varse"
            command: |
              echo "PASSCODE=12345" >> .env
      - run:
            name: "Run Tests"
            command: npm run test:ci
      - store_artifacts:
          path: ./reports/coverage
          destination: coverage
      - store_artifacts:
          path: ./reports/html-report
          destination: report
      - store_test_results:
          path: ./reports/ui-test-results
  e2e:
    working_directory: ~/twilio-voice-notification-app
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - install-dependencies
      - run:
          name: "Install Cypress Dependencies"
          command: cd e2e && npm i
      - run:
          name: "Setting environment vars for e2e"
          command: |
            echo "PASSCODE=12345" >> .env
      - run:
          name: "Serve app && run e2e tests"
          command: npm run test:e2e
      - store_artifacts:
          path: ./e2e/cypress/screenshots
          destination: e2e
      - store_artifacts:
          path: ./e2e/cypress/videos
          destination: e2e
      - store_artifacts:
          path: ./e2e/cypress/results
          destination: e2e
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
  e2e-tests:
    jobs:
      - e2e
